# Generated by Django 5.0.2 on 2024-06-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Lucknow', 'Lucknow'), ('Ahmedabad', 'Ahmedabad'), ('Hyderabad', 'Hyderabad'), ('Vijayawada', 'Vijayawada'), ('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Amaravati', 'Amaravati'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20)),
                ('roomtype', models.CharField(choices=[('Delux', 'Delux'), ('SuperDelux', 'SuperDelux'), ('Suite', 'Suite')], max_length=20)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roomtype',
        ),
        migrations.AlterField(
            model_name='booking',
            name='numberofrooms',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.room'),
            preserve_default=False,
        ),
    ]
