# Generated by Django 5.0.2 on 2024-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
