# Generated by Django 5.0.2 on 2024-11-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='mybookings',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
