# Generated by Django 5.0.2 on 2024-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_returnamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnamount',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
