# Generated by Django 5.0.2 on 2024-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_returnamount_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnamount',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
